name: CompileLinux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Draft a release and and add linux binary
        run: /home/opam/draft_release
